### Spring properties
# Service registers under this name
spring:
  application:
    name: event
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8089
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@proyecto-lucaticket.jief6.mongodb.net/events?retryWrites=true&w=majority
      database: events

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

# HTTP Server (Tomcat) Port
server:
  port: 8091
  # Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  error:
    whitelabel:
      enabled: false


